### ISSUE TITLE
Source app rule not honored

### ISSUE THREAD

**Issue by almightyslug** [pawel-mazurkiewicz/proxly-releases#3]
App version: 1.4.0

I have multiple rules:

**1. Corporate services** - works as expected.
- Type: domain
- Rule: regex:.*?contoso.*?
- Origin application: -
- Priority: 100
- Target browser: Island

**2. Google services** - works as expected.
- Type: domain
- Rule: regex:.*
- Origin application:  -
- Priority: 90
- Target browser: Show browser chooser

**3. URL source app: Slack** - works as expected.
- Type: domain
- Rule: regex:.*
- Origin application: com.timyspeck.slackmacgap
- Priority: 80
- Target browser: Island

**4. URLs source app: emClient** - does not work.
- Type: domain
- Rule: regex:.*
- Origin application: com.emclient.mail.client
- Priority: 70
- Target browser: Show browser chooser

**Expected behavior**
When I click a link in emClient that does not fall under rules [1] or [2], the Browser Chooser appears, and I select the preferred browser to open a link in.

**Actual behavior**
Default Behavior from the app settings is being used.

When the Default Behavior mode is "Open fallback browser," the URL is opened in my fallback browser; the notification of the fallback browser is not being displayed despite the setting being enabled in both the app and macOS notifications settings.

**Comment by pawel-mazurkiewicz** [comment]
Hi @almightyslug, I'm sorry the rule doesn't work as expected. I will look into it. I'll install emclient and try to replicate this issue. In the meantime - would you be so kind as to turn on the logging in the settings, retry your flow and then send resulting log file from `~/Library/Application Support/Proxly/Logs/proxly-DATE.log` - you may, of course, choose to redact any links or information you don't want included, but this might help me resolve this issue for you.

**Comment by pawel-mazurkiewicz** [comment]
By the way, have you tried disabling the other wildcards rules and leaving just the emclient one and see if it works then? I have a hunch that there might be some priority issue here.

**Comment by pawel-mazurkiewicz** [comment]
Alright, I've given it some thought and tried to reproduce the issue. You made me discover a bug in regex parsing, so thanks - I released 1.4.1 with a fix for that particular issue with pattern of ".\*". 
That being said - I believe a combination of factors might have contributed to your issue. On one hand the app might have been silently crashing because of the pattern used but also I can see that you mostly use the same, wildcard pattern across the board - and I think that's an issue with priorities here. Generally I would advise the most broad settings to have a lower priority. Given that "google services" rule is also .\* and with a higher priority it supersedes the emClient one. I have installed emClient and created rule set as you outlined and the links opened from emClient were caught by rule number 2. When I changed the emClient rule to have a higher priority, it worked as expected.

Hope that helps! Please let me know.

**Comment by almightyslug** [comment]
Hi there. Unfortunately, the fix did not work for me.

I collected the log. Some corporate URLs are redacted, though they should not impact the investigation as the rule for opening links containing `contoso` work fine.
`2025-10-01T05:25:43Z [INFO] CloudKit sync completed successfully
2025-10-01T05:25:58Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T05:25:58Z [INFO] CloudKit sync completed successfully
2025-10-01T05:26:06Z [DEBUG] Processing URL with no opener info provided
2025-10-01T05:26:06Z [INFO] Matched domain rule (domain: *.google.com): Browser prompt for Google services for URL: docs.google.com/spreadsheets/d/<redacted>
2025-10-01T05:26:06Z [INFO] Rule requested selection panel for URL: https://docs.google.com/spreadsheets/d/<redacted>
2025-10-01T05:26:17Z [INFO] Falling back to basic workspace launch for Island.app
2025-10-01T05:26:17Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:26:18Z [INFO] Successfully opened URL https://docs.google.com/<redacted> with target: io.island.Island
2025-10-01T05:26:36Z [DEBUG] Processing URL with no opener info provided
2025-10-01T05:26:36Z [INFO] Matched domain rule (domain: regex:\.*?contoso.*?): Island - Contoso for URL: contoso.atlassian.net/wiki/spaces/CHD/pages/<redacted>/Risk+Management+Policy
2025-10-01T05:26:36Z [INFO] Falling back to basic workspace launch for Island.app
2025-10-01T05:26:36Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:26:36Z [INFO] Successfully opened URL https://contoso.atlassian.net/wiki/spaces/CHD/pages/<redacted> with target: io.island.Island
2025-10-01T05:27:03Z [DEBUG] Processing URL with opener: name=Slack, bundleId=com.tinyspeck.slackmacgap
2025-10-01T05:27:03Z [INFO] Matched domain rule with opener constraint (domain: regex:.*): URL source app: Slack from Slack
2025-10-01T05:27:03Z [INFO] Falling back to basic workspace launch for Island.app
2025-10-01T05:27:03Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:27:03Z [INFO] Successfully opened URL https://www.reddit.com/r/programming/comments/1nbqt4d/largest_npm_compromise_in_history_supply_chain/ with target: io.island.Island
2025-10-01T05:27:26Z [DEBUG] Processing URL with no opener info provided
2025-10-01T05:27:26Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got none
2025-10-01T05:27:26Z [DEBUG] Domain rule matched but opener constraint failed: expected com.emclient.mail.client, got none
2025-10-01T05:27:26Z [INFO] No matching rule found for URL: https://community.sentinelone.com/s/case/500UW00000lA5L8/
2025-10-01T05:27:26Z [INFO] No matching rule found, opening in fallback browser: https://community.sentinelone.com/s/case/500UW00000lA5L8/
2025-10-01T05:27:26Z [INFO] Falling back to basic workspace launch for Safari.app
2025-10-01T05:27:26Z [WARNING] Notifications not enabled, skipping notification: browser_fallback
2025-10-01T05:27:26Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:27:26Z [INFO] Successfully opened URL https://community.sentinelone.com/s/case/500UW00000lA5L8/ with target: com.apple.Safari
2025-10-01T05:28:43Z [INFO] CloudKit sync completed successfully
2025-10-01T05:28:59Z [INFO] Schema is up to date.
2025-10-01T05:28:59Z [INFO] CloudKit account status: CKAccountStatus(rawValue: 1), Environment: Production
2025-10-01T05:28:59Z [DEBUG] Notification authorization status updated: 2
2025-10-01T05:28:59Z [DEBUG] Notification categories configured: 3 categories
2025-10-01T05:28:59Z [DEBUG] Notification authorization status updated: 2
2025-10-01T05:28:59Z [INFO] Notification authorization granted: true
2025-10-01T05:28:59Z [INFO] Notification authorization granted: true
2025-10-01T05:29:00Z [INFO] CloudKit sync completed successfully
2025-10-01T05:29:15Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T05:29:15Z [INFO] CloudKit sync completed successfully
2025-10-01T05:29:20Z [INFO] Loaded 235 installed apps from persistence
2025-10-01T05:29:30Z [INFO] Schema is up to date.
2025-10-01T05:29:30Z [DEBUG] Focus info updated: Optional(Proxly.FocusInfo(isActive: false, authorizationStatus: __C.INFocusStatusAuthorizationStatus, focusName: nil))
2025-10-01T05:29:30Z [DEBUG] Processing URL with opener: name=eM Client, bundleId=com.emclient.mail.client
2025-10-01T05:29:30Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got com.emclient.mail.client
2025-10-01T05:29:30Z [INFO] Matched domain rule with opener constraint (domain: regex:.*): URL source app: emClient from eM Client
2025-10-01T05:29:30Z [INFO] Rule requested selection panel for URL: https://community.sentinelone.com/s/case/500UW00000lA5L8/
2025-10-01T05:29:30Z [INFO] CloudKit account status: CKAccountStatus(rawValue: 1), Environment: Production
2025-10-01T05:29:30Z [DEBUG] Notification authorization status updated: 2
2025-10-01T05:29:30Z [DEBUG] Notification categories configured: 3 categories
2025-10-01T05:29:30Z [DEBUG] Notification authorization status updated: 2
2025-10-01T05:29:30Z [INFO] Notification authorization granted: true
2025-10-01T05:29:30Z [INFO] Notification authorization granted: true
2025-10-01T05:29:32Z [INFO] CloudKit sync completed successfully
2025-10-01T05:29:32Z [WARNING] Settings conflict detected (serverRecordChanged). Awaiting user resolution.
2025-10-01T05:29:32Z [INFO] CloudKit sync completed successfully
2025-10-01T05:29:32Z [INFO] Falling back to basic workspace launch for Island.app
2025-10-01T05:29:32Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:29:32Z [INFO] Successfully opened URL https://community.sentinelone.com/s/case/500UW00000lA5L8/ with target: io.island.Island
2025-10-01T05:29:45Z [DEBUG] Processing URL with no opener info provided
2025-10-01T05:29:45Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got none
2025-10-01T05:29:45Z [DEBUG] Domain rule matched but opener constraint failed: expected com.emclient.mail.client, got none
2025-10-01T05:29:45Z [INFO] No matching rule found for URL: https://community.sentinelone.com/s/case/500UW00000lA5L8/
2025-10-01T05:29:45Z [INFO] No matching rule found, opening in fallback browser: https://community.sentinelone.com/s/case/500UW00000lA5L8/
2025-10-01T05:29:45Z [INFO] Falling back to basic workspace launch for Safari.app
2025-10-01T05:29:45Z [INFO] Notification scheduled: browser_fallback with ID: EFA060C1-1062-4E85-9A1A-731686F0651D
2025-10-01T05:29:45Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:29:45Z [INFO] Successfully opened URL https://community.sentinelone.com/s/case/500UW00000lA5L8/ with target: com.apple.Safari
2025-10-01T05:29:45Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T05:29:45Z [INFO] CloudKit sync completed successfully
2025-10-01T05:30:07Z [DEBUG] Processing URL with no opener info provided
2025-10-01T05:30:07Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got none
2025-10-01T05:30:07Z [DEBUG] Domain rule matched but opener constraint failed: expected com.emclient.mail.client, got none
2025-10-01T05:30:07Z [INFO] No matching rule found for URL: https://community.sentinelone.com/s/case/500UW00000lA5L8/
2025-10-01T05:30:07Z [INFO] No matching rule found, opening in fallback browser: https://community.sentinelone.com/s/case/500UW00000lA5L8/
2025-10-01T05:30:07Z [INFO] Falling back to basic workspace launch for Safari.app
2025-10-01T05:30:07Z [INFO] Notification scheduled: browser_fallback with ID: C08C9EE7-7985-42B7-B1B1-43132E3AA32A
2025-10-01T05:30:07Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:30:07Z [INFO] Successfully opened URL https://community.sentinelone.com/s/case/500UW00000lA5L8/ with target: com.apple.Safari
`

There is a specific curious log portion:
`2025-10-01T05:29:32Z [WARNING] Settings conflict detected (serverRecordChanged). Awaiting user resolution.
2025-10-01T05:29:32Z [INFO] CloudKit sync completed successfully
2025-10-01T05:29:32Z [INFO] Falling back to basic workspace launch for Island.app
2025-10-01T05:29:32Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T05:29:32Z [INFO] Successfully opened URL https://community.sentinelone.com/s/case/500UW00000lA5L8/ with target: io.island.Island`

What I tried here is to click a link in emClient leading to SentinelOne support case. It was expected to launch the Browser Chooser, and it did! The next clicks, however, continued falling under Default Behavior and triggering my fallback browser.

**Comment by almightyslug** [comment]
> By the way, have you tried disabling the other wildcards rules and leaving just the emclient one and see if it works then?

I tried disabling all the other rules, confirming they are labeled DISABLED in the rule list. The issue persists.

Regarding the fallback browser notification I reported not working earlier, it started working; I assume the issue here was in my focus mode.

**Comment by pawel-mazurkiewicz** [comment]
I was a bit perplexed - it seems as if the event that OS had send did not contain the necessary bundle info about the caller. Apparently, it may be the case with kAEGetURL AppleEvent that I currently use for detecting caller. I think I have found a better approach that might help with your issue - I will provide you with a custom prerelease build to test this theory (in my case it never happened that this AppleEvent failed to produce the bundle id, but it obviously happens, as evidenced here). Stay tuned.

**Comment by pawel-mazurkiewicz** [comment]
[Proxly.zip](https://github.com/user-attachments/files/22644131/Proxly.zip) @almightyslug - this is a new build, it includes more ways to detect caller bundle id. It's notarized and signed. If you could kindly download this, drop in replace your existing installation, do again the song and dance with emclient links and see if it works more reliably - if not, I would request logs again. If yes, great, it will be updated to normal build on next update.

**Comment by almightyslug** [comment]
Unfortunately, that did not do the thing. In addition, it will no longer honor other rules. Now, everything falls to the default browser (I tried turning the rules on and off) and the logs got broken not showing anything but:
`2025-10-01T16:00:27Z [INFO] CloudKit sync completed successfully
2025-10-01T16:00:41Z [INFO] CloudKit sync completed successfully
2025-10-01T16:00:57Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:00:57Z [INFO] CloudKit sync completed successfully
2025-10-01T16:01:12Z [INFO] CloudKit sync completed successfully
2025-10-01T16:02:50Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:02:50Z [INFO] CloudKit sync completed successfully
2025-10-01T16:03:05Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:03:05Z [INFO] CloudKit sync completed successfully
2025-10-01T16:03:20Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:03:20Z [INFO] CloudKit sync completed successfully`

**Comment by pawel-mazurkiewicz** [comment]
Make sure it wasn't replaced in being a default browser in the System Settings maybe? It seems weird - I don't want to say "it works on my machine", but functionally for me nothing has changed and if the logs are popping up at all in the file after updating, then it means they work, there is no mechanism forwarding different levels of logs to the files, so it seems suspicious that there are no indication of processing url at all, even if they all went to fallback browser, which would be noted in the logs. Given that you mentioned that you use fallback notifications, I'd expect to see these when links are routed to fallback, which are not mentioned by you nor in the logs provided, so Proxly not being default browser at this moment is my best theory.

**Comment by almightyslug** [comment]
My bad, the default browser actually got replaced with another browser app after I manually installed this new version. However, the issue persists. Here are the logs:
`
2025-10-01T16:00:27Z [INFO] CloudKit sync completed successfully
2025-10-01T16:00:41Z [INFO] CloudKit sync completed successfully
2025-10-01T16:00:57Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:00:57Z [INFO] CloudKit sync completed successfully
2025-10-01T16:01:12Z [INFO] CloudKit sync completed successfully
2025-10-01T16:02:50Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:02:50Z [INFO] CloudKit sync completed successfully
2025-10-01T16:03:05Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:03:05Z [INFO] CloudKit sync completed successfully
2025-10-01T16:03:20Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T16:03:20Z [INFO] CloudKit sync completed successfully
2025-10-01T19:03:06Z [INFO] Schema is up to date.
2025-10-01T19:03:06Z [DEBUG] Focus info updated: Optional(Proxly.FocusInfo(isActive: false, authorizationStatus: __C.INFocusStatusAuthorizationStatus, focusName: nil))
2025-10-01T19:03:06Z [DEBUG] Processing URL with opener: name=eM Client, bundleId=com.emclient.mail.client
2025-10-01T19:03:06Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got com.emclient.mail.client
2025-10-01T19:03:06Z [INFO] Matched domain rule with opener constraint (domain: regex:.*): URL source app: emClient from eM Client
2025-10-01T19:03:07Z [INFO] Rule requested selection panel for URL: https://github.com/pawel-mazurkiewicz/proxly-releases/issues/3#issuecomment-3357439604
2025-10-01T19:03:07Z [INFO] CloudKit account status: CKAccountStatus(rawValue: 1), Environment: Production
2025-10-01T19:03:07Z [DEBUG] Notification authorization status updated: 2
2025-10-01T19:03:07Z [DEBUG] Notification categories configured: 3 categories
2025-10-01T19:03:07Z [DEBUG] Notification authorization status updated: 2
2025-10-01T19:03:07Z [INFO] Notification authorization granted: true
2025-10-01T19:03:07Z [INFO] Notification authorization granted: true
2025-10-01T19:03:08Z [INFO] CloudKit sync completed successfully
2025-10-01T19:03:13Z [DEBUG] AppleEvent(audit): missing audit token attribute
2025-10-01T19:03:13Z [DEBUG] AppleEvent(esrc): type=shor
2025-10-01T19:03:13Z [DEBUG] AppleEvent(address): type=psn , dataLen=8
2025-10-01T19:03:13Z [DEBUG] AppleEvent(address/psn): PSN present, skipping PSN→PID conversion on modern macOS
2025-10-01T19:03:13Z [DEBUG] AppleEvent(senderPID): missing or invalid sender PID pid=54251
2025-10-01T19:03:13Z [DEBUG] AppleEvent(frontmost): bundleId=com.chillaid.art.Proxly, path=/Applications/Proxly.app
2025-10-01T19:03:13Z [DEBUG] AppleEvent: resolved opener source=frontmost, name=Proxly, bundleId=com.chillaid.art.Proxly, path=/Applications/Proxly.app
2025-10-01T19:03:13Z [DEBUG] Processing URL with opener: name=Proxly, bundleId=com.chillaid.art.Proxly
2025-10-01T19:03:13Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got com.chillaid.art.Proxly
2025-10-01T19:03:13Z [DEBUG] Domain rule matched but opener constraint failed: expected com.emclient.mail.client, got com.chillaid.art.Proxly
2025-10-01T19:03:13Z [INFO] No matching rule found for URL: https://github.com/pawel-mazurkiewicz/proxly-releases/issues/3#issuecomment-3357439604
2025-10-01T19:03:13Z [INFO] No matching rule found, opening in fallback browser: https://github.com/pawel-mazurkiewicz/proxly-releases/issues/3#issuecomment-3357439604
2025-10-01T19:03:13Z [INFO] Falling back to basic workspace launch for Safari.app
2025-10-01T19:03:13Z [INFO] Notification scheduled: browser_fallback with ID: D6B2D4B9-1BE0-4244-9083-142E394C139C
2025-10-01T19:03:13Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T19:03:13Z [INFO] Successfully opened URL https://github.com/pawel-mazurkiewicz/proxly-releases/issues/3#issuecomment-3357439604 with target: com.apple.Safari
2025-10-01T19:03:22Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T19:03:22Z [INFO] CloudKit sync completed successfully
2025-10-01T19:03:35Z [DEBUG] AppleEvent(audit): missing audit token attribute
2025-10-01T19:03:35Z [DEBUG] AppleEvent(esrc): type=shor
2025-10-01T19:03:35Z [DEBUG] AppleEvent(address): type=psn , dataLen=8
2025-10-01T19:03:35Z [DEBUG] AppleEvent(address/psn): PSN present, skipping PSN→PID conversion on modern macOS
2025-10-01T19:03:35Z [DEBUG] AppleEvent(senderPID): pid=54262, bundleId=com.tinyspeck.slackmacgap, path=/Applications/Slack.app
2025-10-01T19:03:35Z [DEBUG] AppleEvent: resolved opener source=senderPID, name=Slack, bundleId=com.tinyspeck.slackmacgap, path=/Applications/Slack.app
2025-10-01T19:03:35Z [DEBUG] Processing URL with opener: name=Slack, bundleId=com.tinyspeck.slackmacgap
2025-10-01T19:03:35Z [INFO] Matched domain rule (domain: regex:\.*?contoso.*?): Island - Contoso for URL: contoso.atlassian.net/servicedesk/customer/portal/67/IS-332
2025-10-01T19:03:35Z [INFO] Falling back to basic workspace launch for Island.app
2025-10-01T19:03:35Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T19:03:35Z [INFO] Successfully opened URL https://contoso.atlassian.net/servicedesk/customer/portal/67/IS-332 with target: io.island.Island
2025-10-01T19:03:38Z [INFO] AppSettings dates are equal, no sync needed
2025-10-01T19:03:38Z [INFO] CloudKit sync completed successfully
2025-10-01T19:03:45Z [DEBUG] AppleEvent(audit): missing audit token attribute
2025-10-01T19:03:45Z [DEBUG] AppleEvent(esrc): type=shor
2025-10-01T19:03:45Z [DEBUG] AppleEvent(address): type=psn , dataLen=8
2025-10-01T19:03:45Z [DEBUG] AppleEvent(address/psn): PSN present, skipping PSN→PID conversion on modern macOS
2025-10-01T19:03:45Z [DEBUG] AppleEvent(senderPID): missing or invalid sender PID pid=54328
2025-10-01T19:03:45Z [DEBUG] AppleEvent(frontmost): bundleId=com.chillaid.art.Proxly, path=/Applications/Proxly.app
2025-10-01T19:03:45Z [DEBUG] AppleEvent: resolved opener source=frontmost, name=Proxly, bundleId=com.chillaid.art.Proxly, path=/Applications/Proxly.app
2025-10-01T19:03:45Z [DEBUG] Processing URL with opener: name=Proxly, bundleId=com.chillaid.art.Proxly
2025-10-01T19:03:45Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got com.chillaid.art.Proxly
2025-10-01T19:03:45Z [DEBUG] Domain rule matched but opener constraint failed: expected com.emclient.mail.client, got com.chillaid.art.Proxly
2025-10-01T19:03:45Z [INFO] No matching rule found for URL: https://github.com/pawel-mazurkiewicz/proxly-releases/issues/3#issuecomment-3357439604
2025-10-01T19:03:45Z [INFO] No matching rule found, opening in fallback browser: https://github.com/pawel-mazurkiewicz/proxly-releases/issues/3#issuecomment-3357439604
2025-10-01T19:03:45Z [INFO] Falling back to basic workspace launch for Safari.app
2025-10-01T19:03:45Z [INFO] Notification scheduled: browser_fallback with ID: 01263A9F-3462-4D8B-A396-88113AA84458
2025-10-01T19:03:45Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T19:03:45Z [INFO] Successfully opened URL https://github.com/pawel-mazurkiewicz/proxly-releases/issues/3#issuecomment-3357439604 with target: com.apple.Safari
2025-10-01T19:04:03Z [INFO] Loaded 235 installed apps from persistence
2025-10-01T19:04:38Z [DEBUG] AppleEvent(audit): missing audit token attribute
2025-10-01T19:04:38Z [DEBUG] AppleEvent(esrc): type=shor
2025-10-01T19:04:38Z [DEBUG] AppleEvent(address): type=psn , dataLen=8
2025-10-01T19:04:38Z [DEBUG] AppleEvent(address/psn): PSN present, skipping PSN→PID conversion on modern macOS
2025-10-01T19:04:38Z [DEBUG] AppleEvent(senderPID): missing or invalid sender PID pid=54350
2025-10-01T19:04:38Z [DEBUG] AppleEvent(frontmost): bundleId=com.chillaid.art.Proxly, path=/Applications/Proxly.app
2025-10-01T19:04:38Z [DEBUG] AppleEvent: resolved opener source=frontmost, name=Proxly, bundleId=com.chillaid.art.Proxly, path=/Applications/Proxly.app
2025-10-01T19:04:38Z [DEBUG] Processing URL with opener: name=Proxly, bundleId=com.chillaid.art.Proxly
2025-10-01T19:04:38Z [DEBUG] Domain rule matched but opener constraint failed: expected com.tinyspeck.slackmacgap, got com.chillaid.art.Proxly
2025-10-01T19:04:38Z [DEBUG] Domain rule matched but opener constraint failed: expected com.emclient.mail.client, got com.chillaid.art.Proxly
2025-10-01T19:04:38Z [INFO] No matching rule found for URL: https://cl.s12.exct.net/?qs=0c7bd5ff0fb1af8e47fb876e0deb9943e5c0dde5cb7f3f877d48cf18b8c5b6f87d9f92fc12941d68ee0905093b3fe5f6f57964cc518cb3a2542d779f75e84fba
2025-10-01T19:04:38Z [INFO] No matching rule found, opening in fallback browser: https://cl.s12.exct.net/?qs=0c7bd5ff0fb1af8e47fb876e0deb9943e5c0dde5cb7f3f877d48cf18b8c5b6f87d9f92fc12941d68ee0905093b3fe5f6f57964cc518cb3a2542d779f75e84fba
2025-10-01T19:04:38Z [INFO] Falling back to basic workspace launch for Safari.app
2025-10-01T19:04:38Z [INFO] Notification scheduled: browser_fallback with ID: 9B405C23-2492-425D-856C-42F7148C36E8
2025-10-01T19:04:38Z [INFO] Successfully launched browser and opened URL via basic workspace
2025-10-01T19:04:38Z [INFO] Successfully opened URL https://cl.s12.exct.net/?qs=0c7bd5ff0fb1af8e47fb876e0deb9943e5c0dde5cb7f3f877d48cf18b8c5b6f87d9f92fc12941d68ee0905093b3fe5f6f57964cc518cb3a2542d779f75e84fba with target: com.apple.Safari
`
